# Generated by Django 5.2.3 on 2025-07-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='department',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='salary',
            new_name='price',
        ),
    ]
