# Generated by Django 5.2.3 on 2025-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='products/'),
            preserve_default=False,
        ),
    ]
